# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@fuchsia_sdk//build_defs:fidl_dart.bzl", "dart_fidl_library")

dart_fidl_library(
    name = "dart",
    library = "//fidl",
)

dart_fidl_library(
    name = "deps",
    library = "//fidl:dependencies",
)

dart_fidl_library(
    name = "fuchsia",
    library = "//fidl:fuchsia",
)
