#!/bin/bash

# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

pushd ../../..

fx ninja -C out/default.zircon host-x64-linux-clang/obj/tools/kazoo/kazoo.debug host-x64-linux-clang/obj/tools/kazoo/kazoo-test.debug

out/default.zircon/host-x64-linux-clang/obj/tools/kazoo/kazoo-test.debug

out/default.zircon/host-x64-linux-clang/obj/tools/fidl/fidlc \
      --json /tmp/syscalls.json \
      --files zircon/syscalls/*.fidl

out/default.zircon/host-x64-linux-clang/obj/tools/kazoo/kazoo.debug \
  --go-syscall-stubs=/tmp/syscalls_fuchsia.go \
  --go-syscall-x86-asm=/tmp/syscalls_fuchsia_amd64.go \
  --go-vdso-keys=/tmp/vdso_keys_fuchsia.go \
  --go-vdso-x86-calls=/tmp/vdso_fuchsia_amd64.s \
  --go-vdso-arm64-calls=/tmp/vdso_fuchsia_arm64.s \
  /tmp/syscalls.json
