// Copyright 2021 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package codegen

const fileTypesSourceTmpl = `
{{- define "Filename:TypesSource" -}}
fidl/{{ .LibraryDots }}/cpp/wire_types.cc
{{- end }}


{{- define "File:TypesSource" -}}
  {{- UseWire -}}
  // WARNING: This file is machine generated by fidlgen.

  #include <{{ .Library | Filename "TypesHeader" }}>

  {{- range .Decls }}
    {{- if Eq .Kind Kinds.Const }}{{ template "Const:TypesSource" . }}{{- end }}
    {{- if Eq .Kind Kinds.Struct }}{{ template "Struct:TypesSource" . }}{{- end }}
    {{- if Eq .Kind Kinds.Union }}{{ template "Union:TypesSource" . }}{{- end }}
    {{- if Eq .Kind Kinds.Table }}{{ template "Table:TypesSource" . }}{{- end }}
  {{- end }}

  {{ EndOfFile }}
{{ end }}

`
