// Copyright 2018 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package codegen

const fileHeaderTmpl = `
{{- define "Filename:Header" -}}
fidl/{{ .LibraryDots }}/cpp/wire.h
{{- end }}


{{- define "File:Header" -}}
{{- UseWire -}}
// WARNING: This file is machine generated by fidlgen.

#pragma once

#include <{{ .Library | Filename "Markers" }}>
#include <{{ .Library | Filename "TypesHeader" }}>
#include <{{ .Library | Filename "MessagingHeader" }}>
{{ range .Dependencies -}}
#include <{{ . | Filename "Header" }}>
{{ end -}}

{{ "" }}

{{ EndOfFile }}
{{ end }}
`
