#!/boot/bin/sh
echo Welcome to magma autorun -- waiting for device
while [ ! -e /dev/class/gpu/000 ]; do
  echo "Device not found, sleeping"
  sleep 1
done
if [ -z ${GTEST_OUTPUT+x} ]; then
  gtest_output_arg=""
else
  gtest_output_arg=--gtest_output=$GTEST_OUTPUT
fi
echo [UNIT TEST START=]
run_test_component magma_unit_tests $gtest_output_arg
run_test_component msd_intel_gen_nonhardware_tests $gtest_output_arg
### Mesa tests
run_test_component mesa_unit_tests $gtest_output_arg
run_test_component fuchsia-pkg://fuchsia.com/magma_intel_gen_nonhardware_tests#meta/state_pool.cmx $gtest_output_arg
run_test_component state_pool_free_list_only $gtest_output_arg
run_test_component state_pool_no_free $gtest_output_arg
run_test_component block_pool_no_free $gtest_output_arg
echo [UNIT TEST END===]
echo [INTEGRATION TEST START=]
run_test_component magma_abi_conformance_tests $gtest_output_arg
run_test_component msd_intel_gen_integration_tests $gtest_output_arg --gtest_filter=-*Stress*
run_test_component vkext $gtest_output_arg
run_test_component vkreadback $gtest_output_arg
echo [INTEGRATION TEST END===]
