# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@subpar//:subpar.bzl", "par_binary")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

par_binary(
    name = "component_runner",
    srcs = ["component_runner.py"],
)
