#!/bin/bash
set -e
ID=`git show $1 | egrep 'Change-Id' | awk '{print $(NF);}'`
URL="https://fuchsia-review.googlesource.com/q/$ID"

echo Opening Change-Id $ID
if [[ "$OSTYPE" == "darwin"* ]]; then
  open $URL
else
  xdg-open $URL
fi
