#!/usr/bin/env bash

# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec $DIR/../zircon/scripts/run-zircon -a arm64 \
    -o $DIR/../out/build-zircon/build-zircon-qemu-arm64 "$@"
