tools/fidl/fidldoc/src/main.rs:2
tools/banjo/banjo/src/main.rs:2
src/sys/cmc/src/main.rs:1
src/sys/cmc/src/opts.rs:3
garnet/bin/rolldice/src/main.rs:2
garnet/bin/net-cli/src/opts.rs:6
garnet/bin/net-cli/src/main.rs:1
garnet/bin/pkg_ctl/src/main.rs:6
garnet/bin/network-speed-test/src/opts.rs:2
garnet/bin/network-speed-test/src/main.rs:1
garnet/bin/pm_build/src/main.rs:2
garnet/bin/setui_client/src/main.rs:2
third_party/rust_crates/vendor/structopt/README.md:5
third_party/rust_crates/vendor/structopt/CHANGELOG.md:5
peridot/bin/voila/src/main.rs:2
garnet/bin/cs/src/main.rs:2
garnet/bin/net_ctl/src/main.rs:1
garnet/bin/net_ctl/src/opts.rs:3
garnet/bin/omaha_client_ctl/src/main.rs:3
build/sdk/tools/merge/src/main.rs:1
build/sdk/tools/merge/src/flags.rs:2
src/connectivity/wlan/wlanstack/src/main.rs:2
src/virtualization/tests/virtio_net_test_util/src/main.rs:2
src/virtualization/tests/virtio_block_test_util/src/main.rs:3
garnet/examples/tcp/tcp_file_sender/src/main.rs:2
garnet/examples/fidl/echo_client_rust_synchronous/src/main.rs:2
garnet/examples/fidl/echo_client_rust/src/main.rs:2
third_party/rust_crates/vendor/structopt/examples/deny_missing_docs.rs:4
third_party/rust_crates/vendor/structopt/tests/author_version_about.rs:3
third_party/rust_crates/vendor/structopt/src/lib.rs:29
third_party/rust_crates/vendor/structopt/examples/subcommand_aliases.rs:2
third_party/rust_crates/vendor/structopt/examples/example.rs:3
third_party/rust_crates/vendor/structopt/examples/doc_comments.rs:3
third_party/rust_crates/vendor/structopt/examples/no_version.rs:2
third_party/rust_crates/vendor/structopt/examples/at_least_two.rs:2
third_party/rust_crates/vendor/structopt/tests/custom-string-parsers.rs:7
third_party/rust_crates/vendor/structopt/examples/basic.rs:2
third_party/rust_crates/vendor/structopt/examples/git.rs:2
third_party/rust_crates/vendor/structopt/tests/nested-subcommands.rs:10
third_party/rust_crates/vendor/structopt/tests/argument_naming.rs:22
third_party/rust_crates/vendor/structopt/examples/raw_attributes.rs:2
third_party/rust_crates/vendor/structopt/tests/arguments.rs:7
third_party/rust_crates/vendor/structopt/tests/doc-comments-help.rs:7
third_party/rust_crates/vendor/structopt/tests/privacy.rs:2
third_party/rust_crates/vendor/structopt/tests/flatten.rs:8
third_party/rust_crates/vendor/structopt/examples/enum_in_args.rs:2
third_party/rust_crates/vendor/structopt/tests/raw_attributes.rs:2
third_party/rust_crates/vendor/structopt/examples/group.rs:2
third_party/rust_crates/vendor/structopt/tests/options.rs:7
third_party/rust_crates/vendor/structopt/examples/flatten.rs:3
third_party/rust_crates/vendor/structopt/tests/flags.rs:4
third_party/rust_crates/vendor/structopt/tests/subcommands.rs:11
third_party/rust_crates/vendor/structopt/examples/enum_tuple.rs:4
third_party/rust_crates/vendor/structopt/examples/simple_group.rs:2
third_party/rust_crates/vendor/structopt/tests/deny-warnings.rs:3
third_party/rust_crates/vendor/structopt/examples/keyvalue.rs:2
third_party/rust_crates/vendor/structopt/examples/rename_all.rs:4
third_party/rust_crates/vendor/structopt-derive/src/lib.rs:8
garnet/bin/wayland/scanner/src/main.rs:2
docs/development/languages/fidl/tutorial/tutorial-rust.md:1
src/connectivity/telephony/tools/qmi-snoop/src/main.rs:2
src/connectivity/wlan/tools/wlantool/src/main.rs:1
src/connectivity/telephony/tools/ril-ctl/src/main.rs:2
src/connectivity/wlan/tools/wlantool/src/opts.rs:12
src/connectivity/wlan/testing/client-smoke-test/src/opts.rs:2
src/connectivity/wlan/testing/client-smoke-test/src/main.rs:1
src/connectivity/wlan/testing/ap-smoke-test/src/opts.rs:2
src/connectivity/wlan/testing/ap-smoke-test/src/main.rs:1
src/connectivity/wlan/testing/client-stress-test/src/opts.rs:2
src/connectivity/wlan/testing/client-stress-test/src/main.rs:1
src/connectivity/bluetooth/tools/bt-snoop/src/main.rs:2
src/connectivity/bluetooth/tools/bt-snoop-cli/src/main.rs:2
src/connectivity/bluetooth/tools/bt-le-peripheral/src/main.rs:2
src/connectivity/bluetooth/tools/bt-avrcp-controller/src/main.rs:2
zircon/third_party/lib/acpica/source/components/resources/rscalc.c:7
zircon/third_party/lib/acpica_r20190108/source/components/resources/rscalc.c:7
src/connectivity/network/netstack3/tools/enclosed_runner/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/netstack_socks/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/easy_netstack_cfg/src/main.rs:2
src/connectivity/network/testing/netemul/runner/helpers/mock_device_settings/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/netstack_intermediary/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/env_build/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/inheritance/src/main.rs:3
src/connectivity/network/testing/netemul/runner/helpers/netstack_cfg/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/dummy_proc/src/main.rs:2
src/connectivity/network/testing/netemul/runner/test/svc_list/src/main.rs:2
