s/magenta/zircon/g
s/MAGENTA/ZIRCON/g
s/Magenta/Zircon/g
s/^mx\([^A-Za-z0-9]\)/zx\1/g
s/^MX\([^A-Za-z0-9]\)/ZX\1/g
s/\([^A-Za-z0-9]\)mx\([^A-Za-z0-9]\)/\1zx\2/g
s/\([^A-Za-z0-9]\)MX\([^A-Za-z0-9]\)/\1ZX\2/g
s/\([^A-Za-z0-9]\)mx$/\1zx/g
s/\([^A-Za-z0-9]\)MX$/\1ZX/g
s/mxtl/fbl/g
s/MXTL/FBL/g
s/mxio/fdio/g
s/MXIO/FDIO/g
s/mxrio/zxrio/g
s/mxsio/zxsio/g
s/MXRIO/ZXRIO/g
s/MXSIO/ZXSIO/g
s/mxcpp/zxcpp/g
s/MXCPP/ZXCPP/g
s/mxr_/zxr_/g
s/MXR_/ZXR_/g
