#!/usr/bin/env bash
# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This script is only used in building the Fuchsia Go toolchain.
# See //third_party/go/BUILD.gn.

set -euo pipefail

readonly SCRIPT_ROOT="$(cd $(dirname ${BASH_SOURCE[0]} ) && pwd)"
readonly TOOL_NAME="go/bin/go"

source "${SCRIPT_ROOT}/exec_tool.sh"
