#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### Run //scripts/build-zircon.sh to build Zircon.
## Arguments are passed to build-zircon.sh; run with -h for details.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

# If `fx set` or `fx build-zircon` has already been run, then the
# explicit `gn gen` run is superfluous and Ninja will do it as needed.
if [[ -r "${ZIRCON_BUILDROOT}/args.gn" ]]; then
  set -- -G "$@"
fi

fx-run-ninja "${FUCHSIA_DIR}/scripts/build-zircon.sh" -t "${FUCHSIA_ARCH}" "$@"
