#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build zircon, then build fuchsia
## Runs exactly `fx build-zircon` followed by `fx build`.
## Arguments are ignored.  To pass arguments, run each step separately.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?

fx-command-run build-zircon
fx-command-run build
