#!/bin/bash
# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### run bootserver for netbooting

## usage: fx netboot [extra bootserver arguments]

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

name_args=()
name="$(get-device-name)"
if [[ -n "$name" ]]; then
  name_args+=("-n" "${name}")
fi

exec "${FUCHSIA_BUILD_DIR}/netboot.sh" "${name_args[@]}" "$@"
