// Copyright 2017 The Fuchsia Authors. All rights reserved.
// This is a GENERATED file. The license governing this file can be found in the LICENSE file.

#define MX_SYS_time_get 0
#define MX_SYS_nanosleep 1
#define MX_SYS_ticks_get 2
#define MX_SYS_ticks_per_second 3
#define MX_SYS_num_cpus 4
#define MX_SYS_version_get 5
#define MX_SYS_handle_close 6
#define MX_SYS_handle_duplicate 7
#define MX_SYS_handle_replace 8
#define MX_SYS_handle_wait_one 9
#define MX_SYS_handle_wait_many 10
#define MX_SYS_object_signal 11
#define MX_SYS_object_signal_peer 12
#define MX_SYS_object_get_property 13
#define MX_SYS_object_set_property 14
#define MX_SYS_object_get_info 15
#define MX_SYS_object_get_child 16
#define MX_SYS_object_bind_exception_port 17
#define MX_SYS_channel_create 18
#define MX_SYS_channel_read 19
#define MX_SYS_channel_write 20
#define MX_SYS_socket_create 21
#define MX_SYS_socket_write 22
#define MX_SYS_socket_read 23
#define MX_SYS_thread_exit 24
#define MX_SYS_thread_create 25
#define MX_SYS_thread_start 26
#define MX_SYS_thread_read_state 27
#define MX_SYS_thread_write_state 28
#define MX_SYS_process_exit 29
#define MX_SYS_process_create 30
#define MX_SYS_process_start 31
#define MX_SYS_process_read_memory 32
#define MX_SYS_process_write_memory 33
#define MX_SYS_job_create 34
#define MX_SYS_task_resume 35
#define MX_SYS_task_kill 36
#define MX_SYS_event_create 37
#define MX_SYS_eventpair_create 38
#define MX_SYS_futex_wait 39
#define MX_SYS_futex_wake 40
#define MX_SYS_futex_requeue 41
#define MX_SYS_waitset_create 42
#define MX_SYS_waitset_add 43
#define MX_SYS_waitset_remove 44
#define MX_SYS_waitset_wait 45
#define MX_SYS_port_create 46
#define MX_SYS_port_queue 47
#define MX_SYS_port_wait 48
#define MX_SYS_port_bind 49
#define MX_SYS_vmo_create 50
#define MX_SYS_vmo_read 51
#define MX_SYS_vmo_write 52
#define MX_SYS_vmo_get_size 53
#define MX_SYS_vmo_set_size 54
#define MX_SYS_vmo_op_range 55
#define MX_SYS_cprng_draw 56
#define MX_SYS_cprng_add_entropy 57
#define MX_SYS_fifo_create 58
#define MX_SYS_fifo_op 59
#define MX_SYS_log_create 60
#define MX_SYS_log_write 61
#define MX_SYS_log_read 62
#define MX_SYS_ktrace_read 63
#define MX_SYS_ktrace_control 64
#define MX_SYS_ktrace_write 65
#define MX_SYS_thread_arch_prctl 66
#define MX_SYS_debug_transfer_handle 67
#define MX_SYS_debug_read 68
#define MX_SYS_debug_write 69
#define MX_SYS_debug_send_command 70
#define MX_SYS_interrupt_create 71
#define MX_SYS_interrupt_complete 72
#define MX_SYS_interrupt_wait 73
#define MX_SYS_mmap_device_io 74
#define MX_SYS_mmap_device_memory 75
#define MX_SYS_io_mapping_get_info 76
#define MX_SYS_vmo_create_contiguous 77
#define MX_SYS_vmar_allocate 78
#define MX_SYS_vmar_destroy 79
#define MX_SYS_vmar_map 80
#define MX_SYS_vmar_unmap 81
#define MX_SYS_vmar_protect 82
#define MX_SYS_bootloader_fb_get_info 83
#define MX_SYS_set_framebuffer 84
#define MX_SYS_clock_adjust 85
#define MX_SYS_pci_get_nth_device 86
#define MX_SYS_pci_claim_device 87
#define MX_SYS_pci_enable_bus_master 88
#define MX_SYS_pci_enable_pio 89
#define MX_SYS_pci_reset_device 90
#define MX_SYS_pci_map_mmio 91
#define MX_SYS_pci_io_write 92
#define MX_SYS_pci_io_read 93
#define MX_SYS_pci_map_interrupt 94
#define MX_SYS_pci_map_config 95
#define MX_SYS_pci_query_irq_mode_caps 96
#define MX_SYS_pci_set_irq_mode 97
#define MX_SYS_pci_init 98
#define MX_SYS_pci_add_subtract_io_range 99
#define MX_SYS_acpi_uefi_rsdp 100
#define MX_SYS_acpi_cache_flush 101
#define MX_SYS_resource_create 102
#define MX_SYS_resource_get_handle 103
#define MX_SYS_resource_do_action 104
#define MX_SYS_resource_connect 105
#define MX_SYS_resource_accept 106
#define MX_SYS_syscall_test_0 107
#define MX_SYS_syscall_test_1 108
#define MX_SYS_syscall_test_2 109
#define MX_SYS_syscall_test_3 110
#define MX_SYS_syscall_test_4 111
#define MX_SYS_syscall_test_5 112
#define MX_SYS_syscall_test_6 113
#define MX_SYS_syscall_test_7 114
#define MX_SYS_syscall_test_8 115

