// Copyright 2017 The Fuchsia Authors. All rights reserved.
// This is a GENERATED file. The license governing this file can be found in the LICENSE file.

#define MX_SYS_time_get 0
#define MX_SYS_nanosleep 1
#define MX_SYS_ticks_get 2
#define MX_SYS_ticks_per_second 3
#define MX_SYS_num_cpus 4
#define MX_SYS_version_get 5
#define MX_SYS_cache_flush 6
#define MX_SYS_handle_close 7
#define MX_SYS_handle_duplicate 8
#define MX_SYS_handle_replace 9
#define MX_SYS_handle_wait_one 10
#define MX_SYS_handle_wait_many 11
#define MX_SYS_handle_wait_async 12
#define MX_SYS_object_signal 13
#define MX_SYS_object_signal_peer 14
#define MX_SYS_object_get_property 15
#define MX_SYS_object_set_property 16
#define MX_SYS_object_get_info 17
#define MX_SYS_object_get_child 18
#define MX_SYS_object_bind_exception_port 19
#define MX_SYS_channel_create 20
#define MX_SYS_channel_read 21
#define MX_SYS_channel_write 22
#define MX_SYS_channel_call 23
#define MX_SYS_socket_create 24
#define MX_SYS_socket_write 25
#define MX_SYS_socket_read 26
#define MX_SYS_thread_exit 27
#define MX_SYS_thread_create 28
#define MX_SYS_thread_start 29
#define MX_SYS_thread_read_state 30
#define MX_SYS_thread_write_state 31
#define MX_SYS_process_exit 32
#define MX_SYS_process_create 33
#define MX_SYS_process_start 34
#define MX_SYS_process_read_memory 35
#define MX_SYS_process_write_memory 36
#define MX_SYS_job_create 37
#define MX_SYS_task_resume 38
#define MX_SYS_task_kill 39
#define MX_SYS_event_create 40
#define MX_SYS_eventpair_create 41
#define MX_SYS_futex_wait 42
#define MX_SYS_futex_wake 43
#define MX_SYS_futex_requeue 44
#define MX_SYS_waitset_create 45
#define MX_SYS_waitset_add 46
#define MX_SYS_waitset_remove 47
#define MX_SYS_waitset_wait 48
#define MX_SYS_port_create 49
#define MX_SYS_port_queue 50
#define MX_SYS_port_wait 51
#define MX_SYS_port_bind 52
#define MX_SYS_vmo_create 53
#define MX_SYS_vmo_read 54
#define MX_SYS_vmo_write 55
#define MX_SYS_vmo_get_size 56
#define MX_SYS_vmo_set_size 57
#define MX_SYS_vmo_op_range 58
#define MX_SYS_cprng_draw 59
#define MX_SYS_cprng_add_entropy 60
#define MX_SYS_fifo0_create 61
#define MX_SYS_fifo0_op 62
#define MX_SYS_fifo_create 63
#define MX_SYS_fifo_read 64
#define MX_SYS_fifo_write 65
#define MX_SYS_log_create 66
#define MX_SYS_log_write 67
#define MX_SYS_log_read 68
#define MX_SYS_ktrace_read 69
#define MX_SYS_ktrace_control 70
#define MX_SYS_ktrace_write 71
#define MX_SYS_mtrace_control 72
#define MX_SYS_debug_transfer_handle 73
#define MX_SYS_debug_read 74
#define MX_SYS_debug_write 75
#define MX_SYS_debug_send_command 76
#define MX_SYS_interrupt_create 77
#define MX_SYS_interrupt_complete 78
#define MX_SYS_interrupt_wait 79
#define MX_SYS_mmap_device_io 80
#define MX_SYS_mmap_device_memory 81
#define MX_SYS_io_mapping_get_info 82
#define MX_SYS_vmo_create_contiguous 83
#define MX_SYS_vmar_allocate 84
#define MX_SYS_vmar_destroy 85
#define MX_SYS_vmar_map 86
#define MX_SYS_vmar_unmap 87
#define MX_SYS_vmar_protect 88
#define MX_SYS_bootloader_fb_get_info 89
#define MX_SYS_set_framebuffer 90
#define MX_SYS_clock_adjust 91
#define MX_SYS_pci_get_nth_device 92
#define MX_SYS_pci_claim_device 93
#define MX_SYS_pci_enable_bus_master 94
#define MX_SYS_pci_enable_pio 95
#define MX_SYS_pci_reset_device 96
#define MX_SYS_pci_map_mmio 97
#define MX_SYS_pci_io_write 98
#define MX_SYS_pci_io_read 99
#define MX_SYS_pci_map_interrupt 100
#define MX_SYS_pci_map_config 101
#define MX_SYS_pci_query_irq_mode_caps 102
#define MX_SYS_pci_set_irq_mode 103
#define MX_SYS_pci_init 104
#define MX_SYS_pci_add_subtract_io_range 105
#define MX_SYS_acpi_uefi_rsdp 106
#define MX_SYS_acpi_cache_flush 107
#define MX_SYS_resource_create 108
#define MX_SYS_resource_get_handle 109
#define MX_SYS_resource_do_action 110
#define MX_SYS_resource_connect 111
#define MX_SYS_resource_accept 112
#define MX_SYS_syscall_test_0 113
#define MX_SYS_syscall_test_1 114
#define MX_SYS_syscall_test_2 115
#define MX_SYS_syscall_test_3 116
#define MX_SYS_syscall_test_4 117
#define MX_SYS_syscall_test_5 118
#define MX_SYS_syscall_test_6 119
#define MX_SYS_syscall_test_7 120
#define MX_SYS_syscall_test_8 121

