// Copyright 2017 The Fuchsia Authors. All rights reserved.
// This is a GENERATED file. The license governing this file can be found in the LICENSE file.

#define MX_SYS_time_get 0
#define MX_SYS_nanosleep 1
#define MX_SYS_handle_close 2
#define MX_SYS_handle_duplicate 3
#define MX_SYS_handle_replace 4
#define MX_SYS_object_wait_one 5
#define MX_SYS_object_wait_many 6
#define MX_SYS_object_wait_async 7
#define MX_SYS_object_wait_cancel 8
#define MX_SYS_object_signal 9
#define MX_SYS_object_signal_peer 10
#define MX_SYS_object_get_property 11
#define MX_SYS_object_set_property 12
#define MX_SYS_object_get_info 13
#define MX_SYS_object_get_child 14
#define MX_SYS_channel_create 15
#define MX_SYS_channel_read 16
#define MX_SYS_channel_write 17
#define MX_SYS_channel_call 18
#define MX_SYS_socket_create 19
#define MX_SYS_socket_write 20
#define MX_SYS_socket_read 21
#define MX_SYS_thread_exit 22
#define MX_SYS_thread_create 23
#define MX_SYS_thread_start 24
#define MX_SYS_thread_read_state 25
#define MX_SYS_thread_write_state 26
#define MX_SYS_process_exit 27
#define MX_SYS_process_create 28
#define MX_SYS_process_start 29
#define MX_SYS_process_read_memory 30
#define MX_SYS_process_write_memory 31
#define MX_SYS_job_create 32
#define MX_SYS_task_bind_exception_port 33
#define MX_SYS_task_resume 34
#define MX_SYS_task_kill 35
#define MX_SYS_event_create 36
#define MX_SYS_eventpair_create 37
#define MX_SYS_futex_wait 38
#define MX_SYS_futex_wake 39
#define MX_SYS_futex_requeue 40
#define MX_SYS_waitset_create 41
#define MX_SYS_waitset_add 42
#define MX_SYS_waitset_remove 43
#define MX_SYS_waitset_wait 44
#define MX_SYS_port_create 45
#define MX_SYS_port_queue 46
#define MX_SYS_port_wait 47
#define MX_SYS_port_bind 48
#define MX_SYS_vmo_create 49
#define MX_SYS_vmo_read 50
#define MX_SYS_vmo_write 51
#define MX_SYS_vmo_get_size 52
#define MX_SYS_vmo_set_size 53
#define MX_SYS_vmo_op_range 54
#define MX_SYS_vmar_allocate 55
#define MX_SYS_vmar_destroy 56
#define MX_SYS_vmar_map 57
#define MX_SYS_vmar_unmap 58
#define MX_SYS_vmar_protect 59
#define MX_SYS_cprng_draw 60
#define MX_SYS_cprng_add_entropy 61
#define MX_SYS_fifo_create 62
#define MX_SYS_fifo_read 63
#define MX_SYS_fifo_write 64
#define MX_SYS_log_create 65
#define MX_SYS_log_write 66
#define MX_SYS_log_read 67
#define MX_SYS_ktrace_read 68
#define MX_SYS_ktrace_control 69
#define MX_SYS_ktrace_write 70
#define MX_SYS_mtrace_control 71
#define MX_SYS_debug_transfer_handle 72
#define MX_SYS_debug_read 73
#define MX_SYS_debug_write 74
#define MX_SYS_debug_send_command 75
#define MX_SYS_interrupt_create 76
#define MX_SYS_interrupt_complete 77
#define MX_SYS_interrupt_wait 78
#define MX_SYS_interrupt_signal 79
#define MX_SYS_mmap_device_io 80
#define MX_SYS_mmap_device_memory 81
#define MX_SYS_io_mapping_get_info 82
#define MX_SYS_vmo_create_contiguous 83
#define MX_SYS_bootloader_fb_get_info 84
#define MX_SYS_set_framebuffer 85
#define MX_SYS_clock_adjust 86
#define MX_SYS_pci_get_nth_device 87
#define MX_SYS_pci_claim_device 88
#define MX_SYS_pci_enable_bus_master 89
#define MX_SYS_pci_enable_pio 90
#define MX_SYS_pci_reset_device 91
#define MX_SYS_pci_map_mmio 92
#define MX_SYS_pci_io_write 93
#define MX_SYS_pci_io_read 94
#define MX_SYS_pci_map_interrupt 95
#define MX_SYS_pci_map_config 96
#define MX_SYS_pci_query_irq_mode_caps 97
#define MX_SYS_pci_set_irq_mode 98
#define MX_SYS_pci_init 99
#define MX_SYS_pci_add_subtract_io_range 100
#define MX_SYS_acpi_uefi_rsdp 101
#define MX_SYS_acpi_cache_flush 102
#define MX_SYS_resource_create 103
#define MX_SYS_resource_get_handle 104
#define MX_SYS_resource_do_action 105
#define MX_SYS_resource_connect 106
#define MX_SYS_resource_accept 107
#define MX_SYS_hypervisor_create 108
#define MX_SYS_hypervisor_op 109
#define MX_SYS_syscall_test_0 110
#define MX_SYS_syscall_test_1 111
#define MX_SYS_syscall_test_2 112
#define MX_SYS_syscall_test_3 113
#define MX_SYS_syscall_test_4 114
#define MX_SYS_syscall_test_5 115
#define MX_SYS_syscall_test_6 116
#define MX_SYS_syscall_test_7 117
#define MX_SYS_syscall_test_8 118

