// Copyright 2017 The Fuchsia Authors
//
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT

#include "constants_priv.h"

.text

.macro movlit reg, literal
mov \reg, #((\literal) & 0xffff)
.ifne (((\literal) >> 16) & 0xffff)
movk \reg, #(((\literal) >> 16) & 0xffff), lsl #16
.endif
.ifne (((\literal) >> 32) & 0xffff)
movk \reg, #(((\literal) >> 32) & 0xffff), lsl #32
.endif
.ifne (((\literal) >> 48) & 0xffff)
movk \reg, #(((\literal) >> 48) & 0xffff), lsl #48
.endif
.endm

FUNCTION(vcpu_resume_start)
    movlit x0, EXIT_TEST_ADDR
    str xzr, [x0]
FUNCTION(vcpu_resume_end)

FUNCTION(vcpu_read_write_state_start)
FUNCTION(vcpu_read_write_state_end)

FUNCTION(guest_set_trap_start)
FUNCTION(guest_set_trap_end)
