#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Device management
#### DEPRECATED
### deprecated: alias for fx emu
## deprecated: alias for fx emu

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?

fx-warn "fx aemu is replaced by fx emu"
fx-warn " running fx emu in 2s..."

sleep 2

fx-command-exec emu "$@"
