#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### clean the build directory and then perform a full build

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?

if [[ "$#" -gt 0 ]]; then
  fx-error "clean-build no longer takes additional arguments, use fx set to alter build parameters"
  exit 1
fi

fx-command-run clean
fx-command-run build
