#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build zircon, then build fuchsia
## Runs exactly `fx build-zircon` followed by `fx build`.
## Arguments are ignored.  To pass arguments, run each step separately.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?

echo >&2 '*** DEPRECATION WARNING ***'
echo >&2 'NOTE! `fx full-build` is obsolete and will be removed soon.'
echo >&2 'Use plain `fx build` instead.  See `fx help build` for details.'
echo >&2 'Now running `fx build`...'

fx-command-run build
