#!/bin/bash
# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### `gn gen` the FUCHSIA_BUILD_DIR

## If FUCHSIA_BUILD_DIR is out/x64, this is simply:
##   gn gen out/x64
## It is useful if one has by some mechanism deleted the ninja artifacts, but
## not the args.gn, e.g. if one CTRL+C's a regen step (gn bug).

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

set -ex

"${FUCHSIA_DIR}/buildtools/gn" gen "$FUCHSIA_BUILD_DIR" "$@"
