#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#### CATEGORY=Internal API
#### DEPRECATED"
### Renamed to `list-build-artifacts`
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh

fx-error "[DEPRECATED] \`fx get-build-artifacts\` has been renamed to \`fx list-build-artifacts\`; if you are seeing this warning in running a remote workflow command, please \`jiri update\` on your *local* machine and try again"