#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
#### REQUIRES_BUILD_DIR=yes
### print the current fuchsia build directory

## equivalent to `fx exec echo ${FUCHSIA_BUILD_DIR}`

echo "${FUCHSIA_BUILD_DIR}"
