#!/bin/bash
# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Diagnostic
### invoke mem tool on target device

## usage: fx mem <arguments to mem>
##
## Example usage:
##
##   fx mem --digest --output --repeat=10

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

case $1 in
  -h|--help)
  fx-command-help
  exit 0
  ;;
esac

fx-command-run run --no-build --no-kill --no-restart-session mem "$@"
