#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Other
### print relevant information about the developer setup

## usage:
##  fx status [--format=text|json]
##

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?
fx-config-read

# Merge our package config with the one in third_party/dart-pkg/pub
fx-command-run merge-package-config \
  --first "$FUCHSIA_DIR/third_party/dart-pkg/pub/package_config.json" \
  --second "${FUCHSIA_DIR}/scripts/status/package_config.json" \
  --out "${FUCHSIA_BUILD_DIR}/fx_status.package_config.json"

cd "${FUCHSIA_BUILD_DIR}"

exec "${PREBUILT_DART_DIR}/bin/dart" \
  --enable-experiment=non-nullable \
  --no-sound-null-safety \
  --packages="${FUCHSIA_BUILD_DIR}/fx_status.package_config.json" \
  "${FUCHSIA_DIR}/scripts/status/bin/main.dart" "$@"
