#!/bin/bash
# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### deprecated: alias for log

## usage: fx syslog [--raw] [flags]
##
## Deprecated: runs fx log

set -o pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.sh || exit $?

fx-warn "fx syslog was renamed -> fx log"
fx-warn "fx klog provides kernel-only logs from netsvc"
sleep 5

fx-command-exec log "$@"
