#!/usr/bin/env python
# Copyright 2016 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import sys

from pylib import args_lib
from pylib import deploy


def main():
  parser = argparse.ArgumentParser(description='Deploys Modular apps.')

  args_lib.add_common_args(parser)
  parser.add_argument('--local-deploy-dir',
                      help='Path to the dir to deploy into. '
                      'If not specified, will deploy to the cdn.')
  parser.add_argument('--stable',
                      help='Update this version as the stable channel.')

  parsed_args = parser.parse_known_args()
  args = parsed_args[0]

  if not args_lib.parse_common_args(args):
    return -1

  return deploy.deploy(args)


if __name__ == '__main__':
  sys.exit(main())
