#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Source tree
### runs clang-tidy on specified files

## Usage: fx clang-tidy [--fix] [--verbose] [--target=TARGET|--files=FILES]
##
##   --fix    Apply recommended fixes
##   --target Run on a specified GN build target
##   --files  List of files on which to run clang-tidy

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?

echo "WARNING: 'fx clang-tidy' is deprecated. Redirecting to:"
echo "  fx lint $@"
fx-command-run lint "$@"
exit $?
