#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### DEPRECATED

echo "DEPRECATED: fx now automatically creates and tracks one's compilation database; this command will soon be deleted."
exit 1
