#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### produce a dump of v1 components in CSV form.
## usage: fx component-surveyor [OUT_FILE]

## This dump includes the following information:
## - The names of all components known to the package server
## - Categorization of components by group
## - Service dependencies between components
## - cmx features used by components

PYTHONPATH="${PYTHONPATH}:${FUCHSIA_DIR}/scripts/component_graph" python3.8 -m surveyor "$@"
