#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### run zircon core-tests

## usage: core-tests [gtest-filter]

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read
${FUCHSIA_DIR}/scripts/run-core-tests.py "${FUCHSIA_DIR}/tools/devshell/emu" "${FUCHSIA_BUILD_DIR}" "${FUCHSIA_BUILD_DIR}/zbi_tests.json" "$@"
