#!/bin/bash
# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Deprecated, please use "ffx debug fidl"

echo "This command is deprecated. Please use \"ffx debug fidl\" instead."
exit 1
