#!/bin/bash
# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### run a fuzz test on target a device

## usage: fx fuzz [subcommand] [...]
##
## For specific subcommand info, run "fx fuzz help".

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
python ${FUCHSIA_DIR}/scripts/fuzzing/main.py "$@"
