#!/usr/bin/env bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Source tree
#### DEPRECATED
### deprecated: This command was used to creates an integration CL to test other CLs in the global
### integration commit queue.

## deprecated: obsolete tool for initiating global integration tests
##
## This script will, however, check for additional integration test recommendations, if any. 

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

function main {
  local command="$(basename ${BASH_SOURCE[0]})"
  fx-warn "'fx $command' is obsolete. CQ executes global integration tests automatically."
  for vendor_extension in ${FUCHSIA_DIR}/vendor/*/scripts/fx-extensions/$command; do
    [[ ! -f "${vendor_extension}" ]] && break # ignore file glob if no matching expansions
    echo
    echo "================================================================================"
    echo "Found a vendor extension for this command at:"
    echo "  ${vendor_extension/$FUCHSIA_DIR\//}"
    echo
    source "${vendor_extension}" "$@"
  done
  return 0 # override non-zero status of completed for loop
}

main "$@"
