#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### symbolize call stacks provided as input

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

# TODO(jeffbrown): Fix symbolize to support arch other than x64
exec "${FUCHSIA_DIR}/zircon/scripts/old-symbolize" \
      --build-dir "${FUCHSIA_BUILD_DIR}" "$@"
