#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Source tree
### regenerates golden files in the source tree

## Usage: fx regen-goldens PATTERN ... [--list] [--reset] [FX_TEST_FLAGS]
##
## Deprecated. See fx check-goldens.

echo "'fx regen-goldens' is deprecated. Please use 'fx check-goldens' instead."
exit 1
