#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Run a ZBI test

## Run `fx run-zbi-test --help` for usage.

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

source "$SCRIPT_DIR"/../lib/vars.sh || exit $?

fx-config-read

"$SCRIPT_DIR"/run-zbi-test.py "$@"
