#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Run a ZBI test

## Run `fx run-boot-test --help` for usage.

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

source "$SCRIPT_DIR"/../lib/vars.sh || exit $?

fx-config-read

"${PREBUILT_PYTHON3_DIR}/bin/python3.8" "$SCRIPT_DIR"/run-boot-test.py "$@"
