#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### start Fuchsia System Recovery in qemu
##
## Run "fx build recovery_image" first.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

qemu_dir="${PREBUILT_QEMU_DIR}/bin"

"${FUCHSIA_DIR}/zircon/scripts/run-zircon" \
  -a "${FUCHSIA_ARCH}" \
  -q "${qemu_dir}" \
  -t "${FUCHSIA_BUILD_DIR}/$(fx-get-qemu-kernel)" \
  -z "${FUCHSIA_BUILD_DIR}/obj/build/images/recovery/recovery-eng/recovery-eng.zbi" \
  "$@"
