#!/bin/bash
# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Other
### Convenience wrapper for running the product size checker.
## usage: fx size-check
##
## Convenience wrapper for running the product size checker.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

ffx --config assembly_enabled=true assembly size-check product --assembly-manifest $FUCHSIA_BUILD_DIR/obj/build/images/fuchsia/fuchsia/images.json --verbose --visualization-dir $FUCHSIA_BUILD_DIR/size_visualization $@
