#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

host="$(get-fuchsia-device-addr)"

#fx-command-exec "ssh" "${host}" "pwd ; pwd"

regexps="$@"

for r in ${regexps}
do
  echo $r
done
