#!/bin/bash

#### CATEGORY=Other
### run zedmon client

## Usage: fx zedmon <zedmon_args>
##
## Executes the zedmon client binary from the prebuilt directory. See
## https://fuchsia.googlesource.com/zedmon for more on zedmon.
##
## Use "fx zedmon -h" to see available subcommands.


source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh

exec "${FUCHSIA_DIR}"/prebuilt/tools/zedmon/zedmon "${@}"
