#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Deprecated, please use "fx debug"

echo "This command is deprecated. Please use \"fx debug\" instead."
exit 1
