#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### Deprecated, please use "ffx debug connect"

echo "This command is deprecated. Please use \"ffx debug connect\" instead."
exit 1
