// Copyright 2019 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_CONNECTIVITY_WLAN_LIB_COMMON_CPP_INCLUDE_WLAN_COMMON_STATUS_CODE_H_
#define SRC_CONNECTIVITY_WLAN_LIB_COMMON_CPP_INCLUDE_WLAN_COMMON_STATUS_CODE_H_

#include <stdint.h>

/**
 * IEEE Std 802.11-2016, 9.4.1.9, Table 9-46
 */
#define WLAN_STATUS_CODE_LIST                                          \
  X(WLAN_STATUS_CODE_SUCCESS, 0)                                       \
  X(WLAN_STATUS_CODE_REFUSED, 1)                                       \
  X(WLAN_STATUS_CODE_TDLS_REJECTED_ALTERNATIVE_PROVIDED, 2)            \
  X(WLAN_STATUS_CODE_TDLS_REJECTED, 3)                                 \
  X(WLAN_STATUS_CODE_SECURITY_DISABLED, 5)                             \
  X(WLAN_STATUS_CODE_UNACCEPTABLE_LIFETIME, 6)                         \
  X(WLAN_STATUS_CODE_NOT_IN_SAME_BSS, 7)                               \
  X(WLAN_STATUS_CODE_REFUSED_CAPABILITIES_MISMATCH, 10)                \
  X(WLAN_STATUS_CODE_DENIED_NO_ASSOCIATION_EXISTS, 11)                 \
  X(WLAN_STATUS_CODE_DENIED_OTHER_REASON, 12)                          \
  X(WLAN_STATUS_CODE_UNSUPPORTED_AUTH_ALGORITHM, 13)                   \
  X(WLAN_STATUS_CODE_TRANSACTION_SEQUENCE_ERROR, 14)                   \
  X(WLAN_STATUS_CODE_CHALLENGE_FAILURE, 15)                            \
  X(WLAN_STATUS_CODE_REJECTED_SEQUENCE_TIMEOUT, 16)                    \
  X(WLAN_STATUS_CODE_DENIED_NO_MORE_STAS, 17)                          \
  X(WLAN_STATUS_CODE_REFUSED_BASIC_RATES_MISMATCH, 18)                 \
  X(WLAN_STATUS_CODE_DENIED_NO_SHORT_PREAMBLE_SUPPORT, 19)             \
  X(WLAN_STATUS_CODE_REJECTED_SPECTRUM_MANAGEMENT_REQUIRED, 22)        \
  X(WLAN_STATUS_CODE_REJECTED_BAD_POWER_CAPABILITY, 23)                \
  X(WLAN_STATUS_CODE_REJECTED_BAD_SUPPORTED_CHANNELS, 24)              \
  X(WLAN_STATUS_CODE_DENIED_NO_SHORT_SLOT_TIME_SUPPORT, 25)            \
  X(WLAN_STATUS_CODE_DENIED_NO_HT_SUPPORT, 27)                         \
  X(WLAN_STATUS_CODE_R0KH_UNREACHABLE, 28)                             \
  X(WLAN_STATUS_CODE_DENIED_PCO_TIME_NOT_SUPPORTED, 29)                \
  X(WLAN_STATUS_CODE_REFUSED_TEMPORARILY, 30)                          \
  X(WLAN_STATUS_CODE_ROBUST_MANAGEMENT_POLICY_VIOLATION, 31)           \
  X(WLAN_STATUS_CODE_UNSPECIFIED_QOS_FAILURE, 32)                      \
  X(WLAN_STATUS_CODE_DENIED_INSUFFICIENT_BANDWIDTH, 33)                \
  X(WLAN_STATUS_CODE_DENIED_POOR_CHANNEL_CONDITIONS, 34)               \
  X(WLAN_STATUS_CODE_DENIED_QOS_NOT_SUPPORTED, 35)                     \
  X(WLAN_STATUS_CODE_REQUEST_DECLINED, 37)                             \
  X(WLAN_STATUS_CODE_INVALID_PARAMETERS, 38)                           \
  X(WLAN_STATUS_CODE_REJECTED_WITH_SUGGESTED_CHANGES, 39)              \
  X(WLAN_STATUS_CODE_STATUS_INVALID_ELEMENT, 40)                       \
  X(WLAN_STATUS_CODE_STATUS_INVALID_GROUP_CIPHER, 41)                  \
  X(WLAN_STATUS_CODE_STATUS_INVALID_PAIRWISE_CIPHER, 42)               \
  X(WLAN_STATUS_CODE_STATUS_INVALID_AKMP, 43)                          \
  X(WLAN_STATUS_CODE_UNSUPPORTED_RSNE_VERSION, 44)                     \
  X(WLAN_STATUS_CODE_INVALID_RSNE_CAPABILITIES, 45)                    \
  X(WLAN_STATUS_CODE_STATUS_CIPHER_OUT_OF_POLICY, 46)                  \
  X(WLAN_STATUS_CODE_REJECTED_FOR_DELAY_PERIOD, 47)                    \
  X(WLAN_STATUS_CODE_DLS_NOT_ALLOWED, 48)                              \
  X(WLAN_STATUS_CODE_NOT_PRESENT, 49)                                  \
  X(WLAN_STATUS_CODE_NOT_QOS_STA, 50)                                  \
  X(WLAN_STATUS_CODE_DENIED_LISTEN_INTERVAL_TOO_LARGE, 51)             \
  X(WLAN_STATUS_CODE_STATUS_INVALID_FT_ACTION_FRAME_COUNT, 52)         \
  X(WLAN_STATUS_CODE_STATUS_INVALID_PMKID, 53)                         \
  X(WLAN_STATUS_CODE_STATUS_INVALID_MDE, 54)                           \
  X(WLAN_STATUS_CODE_STATUS_INVALID_FTE, 55)                           \
  X(WLAN_STATUS_CODE_REQUESTED_TCLAS_NOT_SUPPORTED56, 56)              \
  X(WLAN_STATUS_CODE_INSUFFICIENT_TCLAS_PROCESSING_RESOURCES, 57)      \
  X(WLAN_STATUS_CODE_TRY_ANOTHER_BSS, 58)                              \
  X(WLAN_STATUS_CODE_GAS_ADVERTISEMENT_PROTOCOL_NOT_SUPPORTED, 59)     \
  X(WLAN_STATUS_CODE_NO_OUTSTANDING_GAS_REQUEST, 60)                   \
  X(WLAN_STATUS_CODE_GAS_RESPONSE_NOT_RECEIVED_FROM_SERVER, 61)        \
  X(WLAN_STATUS_CODE_GAS_QUERY_TIMEOUT, 62)                            \
  X(WLAN_STATUS_CODE_GAS_QUERY_RESPONSE_TOO_LARGE, 63)                 \
  X(WLAN_STATUS_CODE_REJECTED_HOME_WITH_SUGGESTED_CHANGES, 64)         \
  X(WLAN_STATUS_CODE_SERVER_UNREACHABLE, 65)                           \
  X(WLAN_STATUS_CODE_REJECTED_FOR_SSP_PERMISSIONS, 67)                 \
  X(WLAN_STATUS_CODE_REFUSED_UNAUTHENTICATED_ACCESS_NOT_SUPPORTED, 68) \
  X(WLAN_STATUS_CODE_INVALID_RSNE, 72)                                 \
  X(WLAN_STATUS_CODE_UAPSD_COEXISTANCE_NOT_SUPPORTED, 73)              \
  X(WLAN_STATUS_CODE_UAPSD_COEX_MODE_NOT_SUPPORTED, 74)                \
  X(WLAN_STATUS_CODE_BAD_INTERVAL_WITH_UAPSD_COEX, 75)                 \
  X(WLAN_STATUS_CODE_ANTI_CLOGGING_TOKEN_REQUIRED, 76)                 \
  X(WLAN_STATUS_CODE_UNSUPPORTED_FINITE_CYCLIC_GROUP, 77)              \
  X(WLAN_STATUS_CODE_CANNOT_FIND_ALTERNATIVE_TBTT, 78)                 \
  X(WLAN_STATUS_CODE_TRANSMISSION_FAILURE, 79)                         \
  X(WLAN_STATUS_CODE_REQUESTED_TCLAS_NOT_SUPPORTED80, 80)              \
  X(WLAN_STATUS_CODE_TCLAS_RESOURCES_EXHAUSTED, 81)                    \
  X(WLAN_STATUS_CODE_REJECTED_WITH_SUGGESTED_BSS_TRANSITION, 82)       \
  X(WLAN_STATUS_CODE_REJECT_WITH_SCHEDULE, 83)                         \
  X(WLAN_STATUS_CODE_REJECT_NO_WAKEUP_SPECIFIED, 84)                   \
  X(WLAN_STATUS_CODE_SUCCESS_POWER_SAVE_MODE, 85)                      \
  X(WLAN_STATUS_CODE_PENDING_ADMITTING_FST_SESSION, 86)                \
  X(WLAN_STATUS_CODE_PERFORMING_FST_NOW, 87)                           \
  X(WLAN_STATUS_CODE_PENDING_GAP_IN_BA_WINDOW, 88)                     \
  X(WLAN_STATUS_CODE_REJECT_UPID_SETTING, 89)                          \
  X(WLAN_STATUS_CODE_REFUSED_EXTERNAL_REASON, 92)                      \
  X(WLAN_STATUS_CODE_REFUSED_AP_OUT_OF_MEMORY, 93)                     \
  X(WLAN_STATUS_CODE_REJECTED_EMERGENCY_SERVICES_NOT_SUPPORTED, 94)    \
  X(WLAN_STATUS_CODE_QUERY_RESPONSE_OUTSTANDING, 95)                   \
  X(WLAN_STATUS_CODE_REJECT_DSE_BAND, 96)                              \
  X(WLAN_STATUS_CODE_TCLAS_PROCESSING_TERMINATED, 97)                  \
  X(WLAN_STATUS_CODE_TS_SCHEDULE_CONFLICT, 98)                         \
  X(WLAN_STATUS_CODE_DENIED_WITH_SUGGESTED_BAND_AND_CHANNEL, 99)       \
  X(WLAN_STATUS_CODE_MCCAOP_RESERVATION_CONFLICT, 100)                 \
  X(WLAN_STATUS_CODE_MAF_LIMIT_EXCEEDED, 101)                          \
  X(WLAN_STATUS_CODE_MCCA_TRACK_LIMIT_EXCEEDED, 102)                   \
  X(WLAN_STATUS_CODE_DENIED_DUE_TO_SPECTRUM_MANAGEMENT, 103)           \
  X(WLAN_STATUS_CODE_DENIED_VHT_NOT_SUPPORTED, 104)                    \
  X(WLAN_STATUS_CODE_ENABLEMENT_DENIED, 105)                           \
  X(WLAN_STATUS_CODE_RESTRICTION_FROM_AUTHORIZED_GDB, 106)             \
  X(WLAN_STATUS_CODE_AUTHORIZATION_DEENABLED, 107)

#define X(STATUS, CODE) STATUS = (CODE),
enum wlan_status_code : uint8_t { WLAN_STATUS_CODE_LIST };
#undef X
using wlan_status_code_t = enum wlan_status_code;

const char* wlan_status_code_str(wlan_status_code_t status);

#endif  // SRC_CONNECTIVITY_WLAN_LIB_COMMON_CPP_INCLUDE_WLAN_COMMON_STATUS_CODE_H_
