# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

package(
    default_visibility = ["//visibility:public"],
)

config_setting(
    name = "arm64",
    values = {
        "cpu": "arm64",
    },
)

config_setting(
    name = "x64",
    values = {
        "cpu": "x64",
    },
)
