#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/image_build_vars.sh

fx-command-run build "${efi_block}" "${fvm_sparse_block}" "${ramdisk_bin}"

exec "${ZIRCON_TOOLS_DIR}/bootserver" --efi "${FUCHSIA_BUILD_DIR}/${efi_block}" \
  --fvm "${FUCHSIA_BUILD_DIR}/${fvm_sparse_block}" \
    "${ZIRCON_BUILD_DIR}/${zircon_bin}" \
    "${FUCHSIA_BUILD_DIR}/${ramdisk_bin}" "$@"