#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### [DEPRECATED] (now an alias for boot)

## [DEPRECATED] (now an alias for boot)
##
## [DEPRECATED] usage: fx boot-paver <type> [--no-data] [bootserver arguments]

echo
echo "boot-paver is no longer needed - just run \`boot\` instead"
echo

# TODO(raggi): remove on or after Jan 6, 2018

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

if [[ "$#" -eq 0 ]]; then
  fx-command-help
  exit 1
fi

# motivational sleep
sleep 5

fx-command-run boot "$@"
