#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build the kernel

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

echo "Building zircon..."
"${FUCHSIA_DIR}/scripts/build-zircon.sh" \
  -t "${FUCHSIA_ARCH}" \
  -j "$(fx-choose-build-concurrency)" \
  "${FUCHSIA_BUILD_ZIRCON_ARGS[@]}" "$@"
