#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### [DEPRECATED] (now an alias for build)

## [DEPRECATED] (now an alias for build)
##
## [DEPRECATED] usage: fx build-paver [extra ninja args]

echo
echo "build-paver is no longer needed - just run \`build\` instead"
echo

# TODO(raggi): remove on or after Jan 6, 2018

# motivational sleep
sleep 5

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

fx-command-run build "$@"
