#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### run the go tool in fuchsia target configuration

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

case "${FUCHSIA_ARCH}" in
	aarch64)
		GOARCH=arm64
		ZARCH=arm64
		;;
	x86-64)
		GOARCH=amd64
		ZARCH=x86-64
		;;
esac
GOROOT="${FUCHSIA_BUILD_DIR}/goroot"

if [[ ! -d "${GOROOT}" ]]; then
	echo >&2 "You must build the goroot before running this command"
	exit 1
fi

ZIRCON_SYSROOT="${ZIRCON_BUILDROOT}/build-user-${ZARCH}/sysroot" GOOS=fuchsia GOARCH=${GOARCH} CGO_ENABLED=1 GOROOT="${GOROOT}" "${GOROOT}/bin/go" "$@"
