#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

"${FUCHSIA_DIR}/scripts/installer/build-installable-userfs.sh" -b "${FUCHSIA_BUILD_DIR}"
echo "After netbooting, please run 'install-fuchsia' on the device to complete the installation."
"${ZIRCON_TOOLS_DIR}/bootserver" \
  "${ZIRCON_BUILD_DIR}/zircon.bin" \
  "${FUCHSIA_BUILD_DIR}/user.bootfs"
