#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### listen for kernel logs.

## This command delegates to the Zircon `loglistener` binary.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

exec "${ZIRCON_TOOLS_DIR}/loglistener" "$@"
