#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

echo "Creating system package"
fx-command-run mksystempkg
echo "Creating efi image"
fx-command-run mkefi
echo "Creating blobstore image"
fx-command-run mkblobstore
echo "Creating fvm image"
fx-command-run mkfvm
echo "All done - ready for boot-paver"
