#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### (deprecated) same as mkzedboot

## usage: fx mkvbootzedboot [options] <usb device>
##  -f  force writing to a non-usb target

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

echo >&2
echo >&2 "mkvbootzedboot is deprecated, use mkzedboot"
echo >&2

sleep 5

fx-command-run mkzedboot "$@"