#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### make a zedboot configuration in a target directory

## usage: fx mkzedboot <root of external drive>
## Builds Fuchsia bootloader and zedboot and copies it to a drive of
## your choice. Makes zedboot the default boot option.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

if [[ $# -ne 1 ]]; then
  fx-command-help
  exit 1
fi

if [[ ! -d "$1" ]]; then
  echo >&2 "error: Drive at $1 does not appear to be mounted."
  exit 1
fi

drive_dir=$1
efi_target_dir="$1/EFI/BOOT"

# Do a zircon build, and copy the bootloader to drive
fx-command-run build-zircon

mkdir -p "${efi_target_dir}"
cp "${ZIRCON_BUILD_DIR}/bootloader/bootx64.efi" "${efi_target_dir}/BOOTX64.EFI"

ZEDBOOT_IMAGE="images/zedboot-${ZIRCON_PROJECT}.bin"

# Build the Zedboot image.
fx-command-run build "$ZEDBOOT_IMAGE"

# Copy zedboot.bin to drive
cp -f "${FUCHSIA_BUILD_DIR}/${ZEDBOOT_IMAGE}" "${drive_dir}/zedboot.bin"

# Set zedboot as the default boot option, with a timeout of 0
# (i.e. boot instantly into zedboot)
rm -f "${drive_dir}/CMDLINE"
echo 'bootloader.default=zedboot bootloader.timeout=0' > "${drive_dir}/CMDLINE"

echo "Bootloader + zedboot loaded to $1"
