#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx_config_read

function usage {
  cat <<END
usage: fx mkzedboot <root of external drive>
Builds Fuchsia bootloader and zedboot and copies it to a drive of
your choice. Makes zedboot the default boot option.
END
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

if [[ ! -d $1 ]]; then
  echo >&2 "error: Drive at $1 does not appear to be mounted."
  exit 1
fi

drive_dir=$1
efi_target_dir="$1/EFI/BOOT"

# Do a zircon build, and copy the bootloader to drive
fx_command_run build-zircon

mkdir -p "${efi_target_dir}"
cp "${ZIRCON_BUILD_DIR}/bootloader/bootx64.efi" "${efi_target_dir}/BOOTX64.EFI"

# Make zedboot
echo "netsvc.netboot=true virtcon.font=18x32" > "${ZIRCON_BUILD_DIR}/CMDLINE"
"${ZIRCON_BUILD_DIR}/tools/mkbootfs" -o "${ZIRCON_BUILD_DIR}/zedboot.bin" \
  "${ZIRCON_BUILD_DIR}/zircon.bin" \
  -C "${ZIRCON_BUILD_DIR}/CMDLINE" "${ZIRCON_BUILD_DIR}/bootdata.bin"

# Copy zedboot.bin to drive
cp "${ZIRCON_BUILD_DIR}/zedboot.bin" "${drive_dir}"

# Set zedboot as the default boot option, with a timeout of 0
# (i.e. boot instantly into zedboot)
echo "bootloader.default=zedboot bootloader.timeout=0" > "${ZIRCON_BUILD_DIR}/CMDLINE"
cp "${ZIRCON_BUILD_DIR}/CMDLINE" ${drive_dir}

echo "Bootloader + zedboot loaded to $1"
