#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### create and publish packages from a build directory

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

function usage {
  cat >&2 <<END
usage: fx publish [--build-dir <DIR>] [--far-key <key file>] [--far-dir <DIR>] [--update-repo <DIR>] [pkg]
Publish packages. If no package name is supplied, all packages from the current
build output will be published.
  --build-dir
    Directory containing the build output
  --far-key
    Key used to sign the package's meta FAR
  --fars-dir
    Directory to be used to build the meta FAR
  --update-repo
    Directory to be used to publish the meta FAR and associated content blobs
END
}

# Create a package manager package and then create update files which are
# published to the local file system. If no package name is supplied, all
# built packages are processed.
function main {
  local build_dir=""
  local fuchsia_dir="${FUCHSIA_DIR}"
  local argz=( "$@" )
  local c=0
  local has_dir=0

  # if an odd number of arguments were supplied, the last one is assumed
  # to be the name of one or more packages to publish
  local len=${#argz[@]}
  if [[ $((len % 2)) -eq 1 ]]; then
    # copy supplied packages one position down
    argz+=("${argz[${len}-1]}")
    # add the flag used by the Python script at the original position
    argz["${len}-1"]="--pkgs"
  fi

  # check if a build directory is supplied
  while ((c<=len)); do
    if [[ "${argz[${c}]}" == "--build-dir" ]]; then
      : $(( c += 1 ))
      build_dir="${argz[${c}]}"
      has_dir=1
      break
    fi
    : $(( c += 1 ))
  done

  # no build directory, use the default
  if [[ has_dir -eq 0 ]]; then
    build_dir="${FUCHSIA_BUILD_DIR}"
    argz+=("--build-dir" "${build_dir}")
  elif [[ -z "${build_dir}" ]]; then
    # the arg was passed, but wasn't acutally set
    echo >&2 "error: Build directory is not set!"
    return -1
  fi

  ${fuchsia_dir}/scripts/publish-package.py "${argz[@]}"
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    usage
    return $rc
  fi
}

main "$@"
