#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

if [[ "$(uname -s)" = "Darwin" ]]; then
  device_date=`date +%Y-%m-%dT%T`
else
  device_date=`date -Iseconds`
fi

echo "Setting device's clock to ${device_date}"
fx_command_run sh "clock --set ${device_date}"
