#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx_config_read

# TODO(jeffbrown): Fix symbolize to support arch other than x86-64
"${FUCHSIA_DIR}/zircon/scripts/symbolize" \
      --build-dir "${FUCHSIA_BUILD_DIR}" -- "$@"
