// Copyright 2022 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use fuchsia_inspect::StringReference;

pub(super) const ARENA_LOG_ROOT: &'static str = "gestures_event_log";

// Some keys are repeated for every event, which makes for an inefficient
// use of space in the Inspect VMO. Optimize that space by using
// `StringReference`s.
lazy_static::lazy_static! {
    // Event types.
    pub(super) static ref TOUCHPAD_EVENT_NODE: StringReference<'static> = "touchpad_event".into();
    pub(super) static ref KEY_EVENT_NODE: StringReference<'static> = "key_event".into();
    pub(super) static ref MISMATCH_EVENT_NODE: StringReference<'static> = "mismatch_event".into();

    // Common properties.
    pub(super) static ref EVENT_TIME_PROP: StringReference<'static> = "driver_monotonic_nanos".into();
    pub(super) static ref ENTRY_LATENCY_PROP: StringReference<'static> = "entry_latency_micros".into();

    // Touchpad-specific properties.
    pub(super) static ref PRESSED_BUTTONS_PROP: StringReference<'static> = "pressed_buttons".into();
    pub(super) static ref CONTACT_STATE_PROP: StringReference<'static> = "contacts".into();
    pub(super) static ref X_POS_PROP: StringReference<'static> = "pos_x_mm".into();
    pub(super) static ref Y_POS_PROP: StringReference<'static> = "pos_y_mm".into();
    // TODO(https://fxbug.dev/108886): normalize to mm.
    pub(super) static ref WIDTH_PROP: StringReference<'static> = "width_raw".into();
    pub(super) static ref HEIGHT_PROP: StringReference<'static> = "height_raw".into();

    // Mismatch-specific properties.
    pub(super) static ref SUMMARY_PROP: StringReference<'static> = "summary".into();
    pub(super) static ref CONTENDER_PROP: StringReference<'static> = "contender".into();
    pub(super) static ref CRITERION_PROP: StringReference<'static> = "criterion".into();
    pub(super) static ref ACTUAL_VALUE_PROP: StringReference<'static> = "actual".into();
    pub(super) static ref MIN_VALUE_PROP: StringReference<'static> = "min_allowed".into();
    pub(super) static ref MAX_VALUE_PROP: StringReference<'static> = "max_allowed".into();
}

// Example JSON dump of inspect tree generated by `gesture_arena`, from a unit test:
//
// ```json
// {
//   "root": {
//     "gestures_event_log": {
//       "0": {
//         "touchpad_event": {
//           "driver_monotonic_nanos": 12300,
//           "entry_latency_micros": 9987,
//           "pressed_buttons": [
//             1
//           ],
//           "contacts": {
//             "1": {
//               "pos_x_mm": 2.0,
//               "pos_y_mm": 3.0
//             },
//             "2": {
//               "pos_x_mm": 40.0,
//               "pos_y_mm": 50.0
//             }
//           }
//         }
//       },
//       "1": {
//         "mismatch_event": {
//           "contender": "utils::StubContender",
//           "summary": "some reason"
//         }
//       },
//       "2": {
//         "mismatch_event": {
//           "actual": 42,
//           "contender": "utils::StubContender",
//           "criterion": "num_goats_teleported",
//           "max_allowed": 30,
//           "min_allowed": 10
//         }
//       },
//       "3": {
//         "key_event": {
//           "driver_monotonic_nanos": 11000000,
//           "entry_latency_micros": 1000
//         }
//       },
//       "4": {
//         "key_event": {
//           "driver_monotonic_nanos": 13000000,
//           "entry_latency_micros": 1000
//         }
//       },
//       "5": {
//         "touchpad_event": {
//           "driver_monotonic_nanos": 18000000,
//           "entry_latency_micros": 1000,
//           "pressed_buttons": [],
//           "contacts": {
//             "1": {
//               "height_raw": 40.0,
//               "pos_x_mm": 2.0,
//               "pos_y_mm": 3.0,
//               "width_raw": 30.0
//             }
//           }
//         }
//       }
//     }
//   }
// }
// ```

// Example `iquery` excerpt from a live device:
//
// ```json5
// core/ui/scene_manager:
//   metadata:
//     filename = fuchsia.inspect.Tree
//     component_url = fuchsia-pkg://fuchsia.com/scene_manager#meta/scene_manager.cm
//     timestamp = 29164361596
//   payload:
//     root:
//       fuchsia.inspect.Stats:
//         allocated_blocks = 2223
//         current_size = 40960
//         deallocated_blocks = 0
//         failed_allocations = 0
//         maximum_size = 307200
//         total_dynamic_children = 1
//       input_pipeline:
//         gestures_event_log:
//           0:
//             touchpad_event:
//               driver_monotonic_nanos = 26342392592
//               entry_latency_micros = 15141
//               pressed_buttons = []
//               contacts:
//                 0:
//                   height_raw = 3230.000000
//                   pos_x_mm = 32.842999
//                   pos_y_mm = 22.349001
//                   width_raw = 2953.000000
//           1:
//             mismatch_event:
//               actual = 0
//               contender = one_finger_drag::InitialContender
//               criterion = num_pressed_buttons
//               max_allowed = 1
//               min_allowed = 1
//           2:
//             mismatch_event:
//               actual = 1
//               contender = scroll::InitialContender
//               criterion = num_contacts
//               max_allowed = 2
//               min_allowed = 2
//           /* ... many entries omitted ... */
//           20:
//             touchpad_event:
//               driver_monotonic_nanos = 26483988141
//               entry_latency_micros = 3716
//               pressed_buttons = []
//               contacts:
//                 0:
//                   height_raw = 3876.000000
//                   pos_x_mm = 32.811001
//                   pos_y_mm = 22.857000
//                   width_raw = 2953.000000
//           21:
//             mismatch_event:
//               contender = click::UnpressedContender
//               summary = too much motion
//           22:
//             mismatch_event:
//               contender = primary_tap::FingerContactContender
//               summary = too much motion
//           23:
//             mismatch_event:
//               contender = secondary_tap::OneFingerContactContender
//               summary = too much motion
//           /* ... many entries omitted ... */
//           160:
//             touchpad_event:
//               driver_monotonic_nanos = 27562122835
//               entry_latency_micros = 7132
//               pressed_buttons = []
//               contacts:
// ```
