# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

exports_files(
    glob(["*.bzl"]),
)

py_binary(
    name = "package_verifier",
    srcs = ["package_verifier.py"],
)
