// Copyright 2022 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_PROC_LIB_LINUX_UAPI_STUB_MISSING_INCLUDES_H_
#define SRC_PROC_LIB_LINUX_UAPI_STUB_MISSING_INCLUDES_H_

// Adding includes that are not detected by rust-bindings because they are
// defined using functions

#include <asm/ioctls.h>

const __u32 _TIOCSPTLCK = TIOCSPTLCK;
#undef TIOCSPTLCK
const __u32 TIOCSPTLCK = _TIOCSPTLCK;

const __u32 _TIOCGPTLCK = TIOCGPTLCK;
#undef TIOCGPTLCK
const __u32 TIOCGPTLCK = _TIOCGPTLCK;

const __u32 _TIOCGPKT = TIOCGPKT;
#undef TIOCGPKT
const __u32 TIOCGPKT = _TIOCGPKT;

const __u32 _TIOCSIG = TIOCSIG;
#undef TIOCSIG
const __u32 TIOCSIG = _TIOCSIG;

const __u32 _TIOCGPTN = TIOCGPTN;
#undef TIOCGPTN
const __u32 TIOCGPTN = _TIOCGPTN;

const __u32 _BINDER_WRITE_READ = BINDER_WRITE_READ;
#undef BINDER_WRITE_READ
const __u32 BINDER_WRITE_READ = _BINDER_WRITE_READ;

const __u32 _BINDER_SET_IDLE_TIMEOUT = BINDER_SET_IDLE_TIMEOUT;
#undef BINDER_SET_IDLE_TIMEOUT
const __u32 BINDER_SET_IDLE_TIMEOUT = _BINDER_SET_IDLE_TIMEOUT;

const __u32 _BINDER_SET_MAX_THREADS = BINDER_SET_MAX_THREADS;
#undef BINDER_SET_MAX_THREADS
const __u32 BINDER_SET_MAX_THREADS = _BINDER_SET_MAX_THREADS;

const __u32 _BINDER_SET_IDLE_PRIORITY = BINDER_SET_IDLE_PRIORITY;
#undef BINDER_SET_IDLE_PRIORITY
const __u32 BINDER_SET_IDLE_PRIORITY = _BINDER_SET_IDLE_PRIORITY;

const __u32 _BINDER_SET_CONTEXT_MGR = BINDER_SET_CONTEXT_MGR;
#undef BINDER_SET_CONTEXT_MGR
const __u32 BINDER_SET_CONTEXT_MGR = _BINDER_SET_CONTEXT_MGR;

const __u32 _BINDER_THREAD_EXIT = BINDER_THREAD_EXIT;
#undef BINDER_THREAD_EXIT
const __u32 BINDER_THREAD_EXIT = _BINDER_THREAD_EXIT;

const __u32 _BINDER_VERSION = BINDER_VERSION;
#undef BINDER_VERSION
const __u32 BINDER_VERSION = _BINDER_VERSION;

const __u32 _BINDER_GET_NODE_DEBUG_INFO = BINDER_GET_NODE_DEBUG_INFO;
#undef BINDER_GET_NODE_DEBUG_INFO
const __u32 BINDER_GET_NODE_DEBUG_INFO = _BINDER_GET_NODE_DEBUG_INFO;

const __u32 _BINDER_GET_NODE_INFO_FOR_REF = BINDER_GET_NODE_INFO_FOR_REF;
#undef BINDER_GET_NODE_INFO_FOR_REF
const __u32 BINDER_GET_NODE_INFO_FOR_REF = _BINDER_GET_NODE_INFO_FOR_REF;

const __u32 _BINDER_SET_CONTEXT_MGR_EXT = BINDER_SET_CONTEXT_MGR_EXT;
#undef BINDER_SET_CONTEXT_MGR_EXT
const __u32 BINDER_SET_CONTEXT_MGR_EXT = _BINDER_SET_CONTEXT_MGR_EXT;

const __u32 _BINDER_FREEZE = BINDER_FREEZE;
#undef BINDER_FREEZE
const __u32 BINDER_FREEZE = _BINDER_FREEZE;

const __u32 _BINDER_GET_FROZEN_INFO = BINDER_GET_FROZEN_INFO;
#undef BINDER_GET_FROZEN_INFO
const __u32 BINDER_GET_FROZEN_INFO = _BINDER_GET_FROZEN_INFO;

const __u32 _BINDER_ENABLE_ONEWAY_SPAM_DETECTION = BINDER_ENABLE_ONEWAY_SPAM_DETECTION;
#undef BINDER_ENABLE_ONEWAY_SPAM_DETECTION
const __u32 BINDER_ENABLE_ONEWAY_SPAM_DETECTION = _BINDER_ENABLE_ONEWAY_SPAM_DETECTION;

#endif  // SRC_PROC_LIB_LINUX_UAPI_STUB_MISSING_INCLUDES_H_
