// Copyright 2021 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use {
    std::path::PathBuf,
    {argh::FromArgs, ffx_core::ffx_command},
};

#[ffx_command()]
#[derive(FromArgs, Debug, PartialEq)]
#[argh(
    subcommand,
    name = "static-pkgs",
    description = "Check the static packages extracted from the ZBI against golden files",
    example = "To verify static packages on your current build:

        $ ffx scrutiny verify static-pkgs \
            --build-path $(fx get-build-dir) \
            --blobfs-manifest path/to/blob.manifest \
            --golden path/to/golden"
)]
pub struct Command {
    /// path to root output directory of build.
    #[argh(option)]
    pub build_path: PathBuf,
    /// path to ZBI image generated from build.
    #[argh(option)]
    pub zbi: PathBuf,
    /// path to blobfs manifest file generated by the build.
    #[argh(option)]
    pub blobfs_manifest: PathBuf,
    /// path(s) to golden file(s) used to verify routes.
    #[argh(option)]
    pub golden: Vec<PathBuf>,
}
