#!/bin/bash

# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

# Use this to use git bisect with prebuilt binary artifacts. To use, run
#   git bisect start <bad> <good>
#   git bisect run scripts/bisect-helper
# The script will download the prebuilt magenta.bin associated with each commit, if it exists, and
# start it up in qemu. After qemu exits, the script will ask if the build is good or bad.  Type 'y'
# or 'n' and the bisect will proceed.

set -e

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

readonly TEMP_DIR="$(mktemp -d)"
readonly CURRENT_COMMIT="$(git rev-parse HEAD)"
readonly MAGENTA_BIN_URL="https://storage-download.googleapis.com/fuchsia-build/magenta/pc-x86-64/magenta.bin/${CURRENT_COMMIT}"
readonly DOWNLOAD_STATUS="$(curl -s -w %{http_code} --progress-bar --output "${TEMP_DIR}/magenta.bin" "${MAGENTA_BIN_URL}")"
if [[ "${DOWNLOAD_STATUS}" != 200 ]]; then
    echo "Could not find prebuilt at ${MAGENTA_BIN_URL}: ${DOWNLOAD_STATUS}"
    exit 125  # could not evaluate this commit, no prebuilt available
fi

"${DIR}/run-magenta-x86-64" -o "${TEMP_DIR}"
echo "Did it work? y/n"
read RESULT
if [[ "${RESULT}" == y ]]; then
    exit 0
else
    exit 1
fi
