#!/bin/sh

# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

export PROJECT=magenta-pc-uefi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/make-parallel $PROJECT || exit

BUILDDIR=build-$PROJECT
BOOTDIR=scripts/build-magenta-pixel2-deps

FUTILITY=futility

$FUTILITY --debug vbutil_kernel \
          --pack $BUILDDIR/pixel2_kernel.bin \
          --keyblock $BOOTDIR/kernel.keyblock \
          --signprivate $BOOTDIR/kernel_data_key.vbprivk \
          --version 1 \
          --config $BOOTDIR/config.txt \
          --bootloader $BOOTDIR/bootstub.efi \
          --vmlinuz $BUILDDIR/lk.bin

