#!/usr/bin/env bash

# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

ZIRCON_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLANG_DIR="${ZIRCON_ROOT}/prebuilt/downloads/clang/bin"
CLANG_FMT="${CLANG_DIR}/clang-format"

exec "$CLANG_FMT" -i -style=file "$@"
