#!/usr/bin/env bash

# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

NEW_SCRIPT="$(dirname "${BASH_SOURCE[0]}")/download-prebuilt"
echo >&2 "WARNING: $0 is OBSOLETE!"
echo >&2 "WARNING: Use $NEW_SCRIPT instead."

exec "$NEW_SCRIPT" "$@"
