#!/bin/bash
# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "[DEPRECATED] TODO(fxbug.dev/60881): this script is deprecated; for the old functionality please run \`fx vendor google fetch-build-artifacts\`"