#!/usr/bin/env bash

# Copyright 2017 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

# NOTE: Placeholder file for now.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec $DIR/fastboot-flash -b imx8mevk -M 0x40000000 -K 0x0480000 -P boot_a -z "$@"
