#!/usr/bin/env bash

# Copyright 2017 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

# Change to the zircon directory.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SCRIPT_DIR}/.."

for h2md in ../out/build-*/tools/h2md ;
do
    echo $h2md
    break;
done

find system/ -name \*.h -or -name \*.c -or -name \*.cpp | xargs grep '//@doc(' -l | xargs $h2md -v
