#!/bin/bash
# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### Test the helper functions defined in //tools/devshell/lib/fvm.sh

BT_FILE_DEPS=(
  "tools/devshell/lib/fvm.sh"
)

BT_SET_UP() {
  source "${BT_TEMP_DIR}/tools/devshell/lib/fvm.sh"

  FUCHSIA_BUILD_DIR="${BT_TEMP_DIR}/out"
  mkdir "${FUCHSIA_BUILD_DIR}"

  # These paths are expected to be relative to ${FUCHSIA_BUILD_DIR}.
  IMAGE_FVM_RAW="fvm_test-fake_fvm.raw"
  IMAGE_FVM_SPARSE="fvm_test-fake_fvm.sparse"
  IMAGE_FVM_FASTBOOT="fvm_test-fake_fvm.fastboot"
  touch "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}"
  touch "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_SPARSE}"
  touch "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_FASTBOOT}"
}

TEST_fx-fvm-find-raw-source() {
  # If all FVM files are present, we should use raw by default.
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" \
      "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}"
}

TEST_fx-fvm-find-raw-source_no_raw_path() {
  # If the raw FVM path is missing, fall back to sparse FVM.
  unset IMAGE_FVM_RAW
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" \
      "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_SPARSE}"
}

TEST_fx-fvm-find-raw-source_no_raw_or_sparse_path() {
  # If the raw and sparse FVM paths are missing, fall back to fastboot FVM.
  unset IMAGE_FVM_RAW
  unset IMAGE_FVM_SPARSE
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" \
      "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_FASTBOOT}"
}

TEST_fx-fvm-find-raw-source_no_paths() {
  # If all FVM paths are missing, output should be empty.
  unset IMAGE_FVM_RAW
  unset IMAGE_FVM_SPARSE
  unset IMAGE_FVM_FASTBOOT
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" ""
}

TEST_fx-fvm-find-raw-source_no_raw_file() {
  # If the raw FVM file is missing, fall back to sparse FVM.
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}"
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" \
      "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_SPARSE}"
}

TEST_fx-fvm-find-raw-source_no_raw_or_sparse_files() {
  # If the raw and sparse FVM files are missing, fall back to fastboot FVM.
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}"
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_SPARSE}"
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" \
      "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_FASTBOOT}"
}

TEST_fx-fvm-find-raw-source_no_files() {
  # If all FVM files are missing, output should be empty.
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_RAW}"
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_SPARSE}"
  rm "${FUCHSIA_BUILD_DIR}/${IMAGE_FVM_FASTBOOT}"
  BT_ASSERT_EQ "$(fx-fvm-find-raw-source)" ""
}

BT_RUN_TESTS "$@"
