// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Context contains all of the dynamic configuration values for building
// Fuchsia. These values are context-dependent in that they vary based on git
// history and local filesystem layout, so they can only be known at runtime and
// cannot come from data checked into version control.
type Context struct {
	// An absolute path to the root of the Fuchsia checkout.
	CheckoutDir string `protobuf:"bytes,1,opt,name=checkout_dir,json=checkoutDir,proto3" json:"checkout_dir,omitempty"`
	// An absolute path to the build output directory.
	BuildDir string `protobuf:"bytes,2,opt,name=build_dir,json=buildDir,proto3" json:"build_dir,omitempty"`
	// An absolute path to a directory where build artifacts intended to be
	// exposed to the caller should be written.
	ArtifactDir string `protobuf:"bytes,3,opt,name=artifact_dir,json=artifactDir,proto3" json:"artifact_dir,omitempty"`
	// Files changed in the commit being tested.
	ChangedFiles []*Context_ChangedFile `protobuf:"bytes,4,rep,name=changed_files,json=changedFiles,proto3" json:"changed_files,omitempty"`
	// Passed through to the sdk_id gn arg.
	SdkId                string   `protobuf:"bytes,5,opt,name=sdk_id,json=sdkId,proto3" json:"sdk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetCheckoutDir() string {
	if m != nil {
		return m.CheckoutDir
	}
	return ""
}

func (m *Context) GetBuildDir() string {
	if m != nil {
		return m.BuildDir
	}
	return ""
}

func (m *Context) GetArtifactDir() string {
	if m != nil {
		return m.ArtifactDir
	}
	return ""
}

func (m *Context) GetChangedFiles() []*Context_ChangedFile {
	if m != nil {
		return m.ChangedFiles
	}
	return nil
}

func (m *Context) GetSdkId() string {
	if m != nil {
		return m.SdkId
	}
	return ""
}

type Context_ChangedFile struct {
	// Relative path to the file within the checkout.
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context_ChangedFile) Reset()         { *m = Context_ChangedFile{} }
func (m *Context_ChangedFile) String() string { return proto.CompactTextString(m) }
func (*Context_ChangedFile) ProtoMessage()    {}
func (*Context_ChangedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{0, 0}
}

func (m *Context_ChangedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context_ChangedFile.Unmarshal(m, b)
}
func (m *Context_ChangedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context_ChangedFile.Marshal(b, m, deterministic)
}
func (m *Context_ChangedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context_ChangedFile.Merge(m, src)
}
func (m *Context_ChangedFile) XXX_Size() int {
	return xxx_messageInfo_Context_ChangedFile.Size(m)
}
func (m *Context_ChangedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_Context_ChangedFile.DiscardUnknown(m)
}

var xxx_messageInfo_Context_ChangedFile proto.InternalMessageInfo

func (m *Context_ChangedFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "fint.Context")
	proto.RegisterType((*Context_ChangedFile)(nil), "fint.Context.ChangedFile")
}

func init() { proto.RegisterFile("context.proto", fileDescriptor_b64063be2fc89884) }

var fileDescriptor_b64063be2fc89884 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4f, 0x85, 0x30,
	0x1c, 0xc4, 0x83, 0x0f, 0xde, 0x93, 0x3f, 0xb0, 0x34, 0x31, 0x41, 0x5d, 0xc0, 0x89, 0xa9, 0x83,
	0xee, 0x0e, 0x62, 0x4c, 0x5c, 0x19, 0x5d, 0x48, 0x69, 0x8b, 0xfc, 0x03, 0xa1, 0xa4, 0x2d, 0x89,
	0x9f, 0xd8, 0xcf, 0x61, 0x68, 0x21, 0xbe, 0xa9, 0xed, 0xef, 0xee, 0x9a, 0x3b, 0xc8, 0xb8, 0x9a,
	0xad, 0xfc, 0xb1, 0x74, 0xd1, 0xca, 0x2a, 0x12, 0xf6, 0x38, 0xdb, 0xa7, 0xdf, 0x00, 0x2e, 0xb5,
	0xe7, 0xa4, 0x84, 0x94, 0x0f, 0x92, 0x8f, 0x6a, 0xb5, 0xad, 0x40, 0x9d, 0x07, 0x45, 0x50, 0xc5,
	0x4d, 0x72, 0xb0, 0x77, 0xd4, 0xe4, 0x11, 0xe2, 0x6e, 0xc5, 0x49, 0x38, 0xfd, 0xc6, 0xe9, 0xb7,
	0x0e, 0x6c, 0x62, 0x09, 0x29, 0xd3, 0x16, 0x7b, 0xc6, 0x7d, 0xfe, 0xe4, 0xf3, 0x07, 0xdb, 0x2c,
	0xaf, 0x90, 0xf1, 0x81, 0xcd, 0xdf, 0x52, 0xb4, 0x3d, 0x4e, 0xd2, 0xe4, 0x61, 0x71, 0xaa, 0x92,
	0xe7, 0x7b, 0xba, 0x95, 0xa1, 0x7b, 0x11, 0x5a, 0x7b, 0xcb, 0x07, 0x4e, 0xb2, 0x49, 0xf9, 0xff,
	0xc3, 0x90, 0x3b, 0x38, 0x1b, 0x31, 0xb6, 0x28, 0xf2, 0xc8, 0x7d, 0x1e, 0x19, 0x31, 0x7e, 0x8a,
	0x87, 0x12, 0x92, 0xab, 0x0c, 0x21, 0x10, 0x2e, 0xcc, 0x0e, 0xfb, 0x00, 0x77, 0x7f, 0xbb, 0x7c,
	0x45, 0x6e, 0x77, 0x77, 0x76, 0xc7, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x28, 0x25,
	0x0f, 0x0f, 0x01, 0x00, 0x00,
}
