// Copyright 2020 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "surface_fuchsia_key_to_hid.h"

#include <fuchsia/input/c/fidl.h>

#include "common/macros.h"
#include "surface/surface_types.h"

//
// This table depends on C99 designated initializers -- C++ doesn't support indexed initializers.
//

#define SURFACE_FUCHSIA_KEY_MASK 0xFF

#define SURFACE_FUCHSIA_KEY_TO_HID_2(key_, hid_)                                                   \
  [fuchsia_input_Key_##key_ & SURFACE_FUCHSIA_KEY_MASK] = SURFACE_KEY_##hid_

#define SURFACE_FUCHSIA_KEY_TO_HID(symbol_) SURFACE_FUCHSIA_KEY_TO_HID_2(symbol_, symbol_)

static uint8_t const key_to_hid_map[] = {
  SURFACE_FUCHSIA_KEY_TO_HID(A),
  SURFACE_FUCHSIA_KEY_TO_HID(B),
  SURFACE_FUCHSIA_KEY_TO_HID(C),
  SURFACE_FUCHSIA_KEY_TO_HID(D),
  SURFACE_FUCHSIA_KEY_TO_HID(E),
  SURFACE_FUCHSIA_KEY_TO_HID(F),
  SURFACE_FUCHSIA_KEY_TO_HID(G),
  SURFACE_FUCHSIA_KEY_TO_HID(H),
  SURFACE_FUCHSIA_KEY_TO_HID(I),
  SURFACE_FUCHSIA_KEY_TO_HID(J),
  SURFACE_FUCHSIA_KEY_TO_HID(K),
  SURFACE_FUCHSIA_KEY_TO_HID(L),
  SURFACE_FUCHSIA_KEY_TO_HID(M),
  SURFACE_FUCHSIA_KEY_TO_HID(N),
  SURFACE_FUCHSIA_KEY_TO_HID(O),
  SURFACE_FUCHSIA_KEY_TO_HID(P),
  SURFACE_FUCHSIA_KEY_TO_HID(Q),
  SURFACE_FUCHSIA_KEY_TO_HID(R),
  SURFACE_FUCHSIA_KEY_TO_HID(S),
  SURFACE_FUCHSIA_KEY_TO_HID(T),
  SURFACE_FUCHSIA_KEY_TO_HID(U),
  SURFACE_FUCHSIA_KEY_TO_HID(V),
  SURFACE_FUCHSIA_KEY_TO_HID(W),
  SURFACE_FUCHSIA_KEY_TO_HID(X),
  SURFACE_FUCHSIA_KEY_TO_HID(Y),
  SURFACE_FUCHSIA_KEY_TO_HID(Z),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_1, 1),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_2, 2),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_3, 3),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_4, 4),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_5, 5),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_6, 6),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_7, 7),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_8, 8),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_9, 9),
  SURFACE_FUCHSIA_KEY_TO_HID_2(KEY_0, 0),
  SURFACE_FUCHSIA_KEY_TO_HID(ENTER),
  SURFACE_FUCHSIA_KEY_TO_HID(ESCAPE),
  SURFACE_FUCHSIA_KEY_TO_HID(BACKSPACE),
  SURFACE_FUCHSIA_KEY_TO_HID(TAB),
  SURFACE_FUCHSIA_KEY_TO_HID(SPACE),
  SURFACE_FUCHSIA_KEY_TO_HID(MINUS),
  SURFACE_FUCHSIA_KEY_TO_HID(EQUALS),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT_BRACE),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT_BRACE),
  SURFACE_FUCHSIA_KEY_TO_HID(BACKSLASH),
  SURFACE_FUCHSIA_KEY_TO_HID(NON_US_HASH),
  SURFACE_FUCHSIA_KEY_TO_HID(SEMICOLON),
  SURFACE_FUCHSIA_KEY_TO_HID(APOSTROPHE),
  SURFACE_FUCHSIA_KEY_TO_HID(GRAVE_ACCENT),
  SURFACE_FUCHSIA_KEY_TO_HID(COMMA),
  SURFACE_FUCHSIA_KEY_TO_HID(DOT),
  SURFACE_FUCHSIA_KEY_TO_HID(SLASH),
  SURFACE_FUCHSIA_KEY_TO_HID(CAPS_LOCK),
  SURFACE_FUCHSIA_KEY_TO_HID(F1),
  SURFACE_FUCHSIA_KEY_TO_HID(F2),
  SURFACE_FUCHSIA_KEY_TO_HID(F3),
  SURFACE_FUCHSIA_KEY_TO_HID(F4),
  SURFACE_FUCHSIA_KEY_TO_HID(F5),
  SURFACE_FUCHSIA_KEY_TO_HID(F6),
  SURFACE_FUCHSIA_KEY_TO_HID(F7),
  SURFACE_FUCHSIA_KEY_TO_HID(F8),
  SURFACE_FUCHSIA_KEY_TO_HID(F9),
  SURFACE_FUCHSIA_KEY_TO_HID(F10),
  SURFACE_FUCHSIA_KEY_TO_HID(F11),
  SURFACE_FUCHSIA_KEY_TO_HID(F12),
  SURFACE_FUCHSIA_KEY_TO_HID(PRINT_SCREEN),
  SURFACE_FUCHSIA_KEY_TO_HID(SCROLL_LOCK),
  SURFACE_FUCHSIA_KEY_TO_HID(PAUSE),
  SURFACE_FUCHSIA_KEY_TO_HID(INSERT),
  SURFACE_FUCHSIA_KEY_TO_HID(HOME),
  SURFACE_FUCHSIA_KEY_TO_HID(PAGE_UP),
  SURFACE_FUCHSIA_KEY_TO_HID(DELETE),
  SURFACE_FUCHSIA_KEY_TO_HID(END),
  SURFACE_FUCHSIA_KEY_TO_HID(PAGE_DOWN),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT),
  SURFACE_FUCHSIA_KEY_TO_HID(DOWN),
  SURFACE_FUCHSIA_KEY_TO_HID(UP),
  SURFACE_FUCHSIA_KEY_TO_HID(NON_US_BACKSLASH),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT_CTRL),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT_SHIFT),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT_ALT),
  SURFACE_FUCHSIA_KEY_TO_HID(LEFT_META),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT_CTRL),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT_SHIFT),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT_ALT),
  SURFACE_FUCHSIA_KEY_TO_HID(RIGHT_META),
  SURFACE_FUCHSIA_KEY_TO_HID(MENU),
};

//
// NOTE(allanmac): this is useful if we change the map's type
//

STATIC_ASSERT_MACRO_1(ARRAY_LENGTH_MACRO(key_to_hid_map) <= 256);

//
// For now we want to know if this changes
//

uint32_t
surface_fuchsia_key_to_hid(uint32_t key)
{
  uint32_t const key_masked = (key & SURFACE_FUCHSIA_KEY_MASK);

  if (key_masked < ARRAY_LENGTH_MACRO(key_to_hid_map))
    {
      return key_to_hid_map[key_masked];
    }
  else
    {
      return 0;
    }
}

//
//
//
