#!/boot/bin/sh
echo Welcome to magma autorun -- waiting for device
while [ ! -e /dev/class/gpu/000 ]; do
  echo "Device not found, sleeping"
  sleep 1
done
echo [UNIT TEST START=]
/pkgfs/packages/magma_nonhardware_tests/0/test/magma_unit_tests
/pkgfs/packages/magma_arm_mali_nonhardware_tests/0/test/msd_arm_mali_nonhardware_tests
echo [UNIT TEST END===]
echo [INTEGRATION TEST START=]
/system/test/magma_abi_conformance_tests
run_test_component msd_arm_mali_integration_tests
if [ -e /pkgfs/packages/vulkan-tests/0/test/vkext ]; then
  run fuchsia-pkg://fuchsia.com/vulkan-tests#meta/vkext.cmx --gtest_filter=-VulkanExtension.Scanout
  run fuchsia-pkg://fuchsia.com/vulkan-tests#meta/vkreadback.cmx
else
  echo SKIPPED app tests - no /pkgfs/packages/vulkan-tests/0/test/vkext
fi
echo [INTEGRATION TEST END===]
