#!/boot/bin/sh
echo Welcome to magma autorun -- waiting for device
while [ ! -e /dev/class/gpu/000 ]; do
  echo "Device not found, sleeping"
  sleep 1
done
echo [UNIT TEST START=]
/system/test/magma_unit_tests
/system/test/msd_arm_mali_nonhardware_tests
echo [UNIT TEST END===]
echo [INTEGRATION TEST START=]
/system/test/magma_abi_conformance_tests --gtest_filter=-*Display*:MagmaAbi.WaitRendering
if [ -e /system/test/magma_arm_integration_tests ]; then
  /system/test/magma_arm_integration_tests
else
  echo SKIPPED /system/test/magma_arm_integration_tests
fi
if [ -e /system/test/vkext ]; then
  /system/test/vkext --gtest_filter=-VulkanExtension.Scanout
  /system/test/vkreadback
else
  echo SKIPPED app tests - no /system/test/vkext
fi
echo [INTEGRATION TEST END===]
