#!/boot/bin/sh
echo Welcome to magma autorun -- waiting for device
while [ ! -e /dev/class/gpu/000 ]; do
  echo "Device not found, sleeping"
  sleep 1
done
if [ -z ${GTEST_OUTPUT+x} ]; then
  gtest_output_arg=""
else
  gtest_output_arg=--gtest_output=$GTEST_OUTPUT
fi
echo [UNIT TEST START=]
/pkgfs/packages/magma_nonhardware_tests/0/test/magma_unit_tests
/pkgfs/packages/magma_intel_gen_nonhardware_tests/0/test/msd_intel_gen_nonhardware_tests
### Mesa tests
/pkgfs/packages/magma_intel_gen_nonhardware_tests/0/test/mesa_unit_tests
/pkgfs/packages/magma_intel_gen_nonhardware_tests/0/test/state_pool
/pkgfs/packages/magma_intel_gen_nonhardware_tests/0/test/state_pool_free_list_only
/pkgfs/packages/magma_intel_gen_nonhardware_tests/0/test/state_pool_no_free
echo [UNIT TEST END===]
echo [INTEGRATION TEST START=]
run_test_component magma_abi_conformance_tests $gtest_output_arg
/system/test/msd_intel_gen_integration_tests --gtest_filter=-*Stress*
run_test_component vkext $gtest_output_arg
run_test_component vkreadback $gtest_output_arg
echo [INTEGRATION TEST END===]
