#!/boot/bin/sh
echo Welcome to magma autorun -- waiting for device
while [ ! -e /dev/class/gpu/000 ]; do
  echo "Device not found, sleeping"
  sleep 1
done
echo [MSD-ARM-MALI START=]
/system/test/msd_arm_mali_nonhardware_tests
echo [MSD-ARM-MALI END===]
echo [SYS START=]
/system/test/magma_sys_unit_tests
echo [SYS END===]
echo [==========]
echo [ABI START=]
/system/test/magma_abi_conformance_tests --gtest_filter=-*Display*:MagmaAbi.WaitRendering
echo [ABI END===]
echo [==========]

if [ -e /system/test/magma_arm_integration_tests ]; then
  echo [INTEGRATION START=]
  /system/test/magma_arm_integration_tests
  echo [INTEGRATION END===]
  echo [==========]
else
  echo SKIPPED /system/test/magma_arm_integration_tests
fi

if [ -e /system/test/vkext ]; then
  echo [APP START=]
  /system/test/vkext --gtest_filter=-VulkanExtension.Scanout
  /system/test/vkreadback
  echo [APP END===]
  echo [==========]
else
  echo SKIPPED app tests - no /system/test/vkext
fi
